### ISSUE TITLE
Set API version in request headers, not URL

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/nailgun#102]
Currently, the requests wrapper in module nailgun.client is very thin. It differs from the wrapped client in the following ways:

It logs information about HTTP requests which go out and the HTTP responses received back.
It sets the content-type to application/json by default.
It automatically encodes request data if the content-type is set to application/json.
One other change should be made:

It sets the "version" header to "2" by default.
Doing this would allow us to change which version of the API is being tested without altering numerous URLs in module nailgun.entities.

Inspired by discussions in https://github.com/SatelliteQE/robottelo/issues/966. Related to https://github.com/SatelliteQE/robottelo/issues/979. And copied from https://github.com/SatelliteQE/robottelo/issues/1043.

**Comment by Ichimonji10** [comment]
Most entities correspond to a set of API paths that contain `/api/v2`. For example:

* `/api/v2`
* `/katello/api/v2`
* `/docker/api/v2/containers`

However, that's not the case for *all* entities. The following are also used:

* `/fusor/api/v21/deployments`
* `/foreman_tasks/api/tasks`

As a result, it's probaby best to continue specifying the API version to use on a per-entity basis. We could continue providing the API version in the path as is done now, as clearly this approach is quite simple and works well. Or we could set header values that should be passed to the client.

Thoughts?

**Comment by elyezer** [comment]
Better consistency for API is the solution, but as we don't have it we need to think on how to deal with it.

As of now, I think we can still use the API version in the URL because working around the inconsistency will demand some work and the result will not pay the debt.

**Comment by elyezer** [comment]
Not so relevant, closing this.
