### ISSUE TITLE
[Failed-AutoCherryPick] - fixing the memory issue in auto-cherry-pick GHA

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/nailgun#1021]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/nailgun/actions/runs/6639764999)
- [Parent Pull Request](https://github.com/SatelliteQE/nailgun/pull/996)

**Comment by omkarkhatavkar** [comment]
Not Required as we are not running this GHA in 6.12.z
