### ISSUE TITLE
x.__init__() got multiple values for argument 'server_config'

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/nailgun#1038]
I know https://github.com/SatelliteQE/nailgun/pull/1029/files fixed a bunch of entities, but some remain.

Applies to Role, Architecture, TablePreferences... I suppose all entities that use create_payload

**Comment by damoore044** [comment]
Blocking stream automation in snap 60.0 (ErrataManagement and likely others)
Reference: **Jenkins/RP > phoenix-content > stream el9 Components > rhel9-ErrataManagement > session # 11**
Test Result: 70/70 fail in setup for this error

**Comment by damoore044** [comment]
Locally reproduced with master nailgun, all tests using `module_org` fail. 
Dropping the commit from #1143 resolved the issue for me.
