### ISSUE TITLE
Implement EntitySearchMixin

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#11]
It'd be super handy to be able to search for entities with a standard search mechanism rather than adding methods to entities on an ad-hoc basis.

**Comment by Ichimonji10** [comment]
Here's a santized version of some notes I wrote up on the subject several weeks ago.

EntitySearchMixin
=================

I think it's about time to create an EntitySearchMixin class. This occurred to me while looking over some Jenkins failures recently. The jenkins failure involved some custom search code, and the process of troubleshooting the search code would be easier if a standard toolset for searching was available. I propose adding an EntitySearchMixin class which provides the following methods:

    search
    └── search_json
        └── search_raw
            └── search_payload

In the near term, the `search` method will not be implemented, as there are some significant barriers to implementing it. However, the other three `search_*` methods can be immediately created.

Search Structure
----------------

When a GET request is issued, a JSON payload must be provided. The payload has this basic structure:

    {
        'filter': '…',
        'filter2': '…',
        'search': 'key=… AND key2=…',
    }

The above is not as easy to implement as it appears at first glance, due to some annoying details. For example, here are some filters named by the API documentation:

* per_page (e.g. 20)
* order (e.g. 'name DESC')
* sort (e.g. {'name', 'DESC'})
* name (e.g. 'ACME Corp')
* organization_id (e.g. 5)

Notice that some of the filters, such as `per_page` and `sort`, are very generic and can apply to all search results, but other filters such as `name` and `organization_id` are specific to the type of entity being searched. Notice also that the `sort` and `order` filters are both very generic, but appear to conflict with each other.

The search string itself is also highly variable. Foreman API paths expect key-value pairs to be joined with the '=' character, whereas Katello API paths expect key-value pairs to be joined with the ':' character. Upstream will unify the syntax over time, but it is not the case right now. Also, search strings are arbitrarily complex. The AND and OR operators may be used, and I suspect that queries can be made more complex by adding parentheses. Also, search terms must be escaped so that characters like '=' do not interfere. The API documentation provides no guidance on how to perform escaping, and some questioning in IRC yielded "my guess is wrap it in double quotes".

Robottelo Search Implementation
-------------------------------

To handle all of the above, here is what I suggest doing:

### Mark Fields

Add a `search_filter=False` argument to `Field.__init__`'s parameter list. This will make it possible to mark individual fields as being filters in a very natural way. For example:

    class Product(…):
        organization = orm.OneToOneField('Organization', required=True, search_filter=True)
        name = orm.StringField(required=True, search_filter=True)
        label = orm.StringField()

### Method Responsibilities

The `search_payload` method should be responsible for generating a payload that can be used in an HTTP GET request. This method is responsible for reading data from the current entity (`vars(self)`) and transforming it in to something that Satellite understands. This means adding "_id" and "_ids" to the end of key names, placing query components either into the search string or using it as a search filter, placing either '=' or ':' in the search string, and so on. Depending on how complex this task is, it may be appropriate to split the search string generation logic into a separate method.

The `search_raw` method should be responsible for making the actual HTTP GET call. A call might look like this:

    Product(organization=5, name='Kool Aid').search_raw(auth=('Alice', 'hackme'))

It may be appropriate to add a facility to passing extra filters at this level. For example:

    Product(organization=5, name='Kool Aid').search_raw(
        filters={'per_page': 30, 'page': 2},
        auth=('Alice', 'hackme'),
    )

Interestingly, this would provide a method of conducting custom searches:

    Product().search_raw(
        filters={
            'per_page': 30,
            'page': 2,
            'organization_id': 5,
            'search': 'description="Purple Flavor!" OR description="Grape Flavor!"',
        },
        auth=('Alice', 'hackme'),
    )

This is an appealing approach. Search strings can be arbitrarily complex, and attempting to provide a layer of abstraction that generates all possible search strings is bound to fail (at the very least, it will be a very poor abstraction).

The `search_json` method should simply check for a status code that indicates an error and JSON-decode the response. It may also be useful to return just the 'results' section of the results instead of the full results. This is an open question.

The `search` method should return a tuple of entity objects that are pre-populated with IDs. No other attributes are pre-populated. Ideally, the full set of attributes for an entity should be lazily populated when an un-populated attribute is accessed, but that is a long-term goal.

Other Info
----------

A functioning `EntitySearchMixin` has been implemented. However, it has some subtle and nasty design issues. It should not be used, and the ideas described above should be implemented instead. Masochists can see the first implementation attempt here: https://github.com/Ichimonji10/robottelo/compare/search-mixin

**Comment by elyezer** [comment]
:+1:

**Comment by Ichimonji10** [comment]
I have an under-development solution in place. The design appears to be robust. Check it out if you're curious: https://github.com/SatelliteQE/nailgun/compare/master...Ichimonji10:search2

```python
>>> from nailgun import entities
>>> sync_plan = entities.SyncPlan(id=6).read()
>>> sync_plans = sync_plan.search(set(), {'organization_id': 1})
>>> len(sync_plans)
1
>>> sync_plans[0].id
6
```

**Comment by elyezer** [comment]
I may be wrong but I suspect that the fields argument will be something not used in most of the cases and maybe the query being the first argument will make the search call better.

**Comment by Ichimonji10** [comment]
@elyezer That's a great idea. It'll let you write queries like this:

    SomeEntity(...).search({'per-page': 50})

**Comment by Ichimonji10** [comment]
I'm psyched to start testing the search mixin. Here's a funky result I received today while manually testing my in-development implementation:

```python
>>> from nailgun import entities
>>> org = entities.Organization()
>>> len(org.search())
424
>>> len(org.search({'name': 'Default Organization'}))
424
>>> len(org.search({'search': 'name="Default Organization"'}))
1
>>> len(org.search({'search': 'name:"Default Organization"'}))
0
```
