### ISSUE TITLE
Implement EntityUpdateMixin

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#12]
It'd be super handy to have a standard mechanism for updating existing entities.

**Comment by Ichimonji10** [comment]
Incomplete solution: https://github.com/Ichimonji10/nailgun/compare/master...Ichimonji10:update-mixin

**Comment by omaciel** [comment]
Beautiful! Looking forward to seeing it in action @Ichimonji10

**Comment by Ichimonji10** [comment]
I've hopefully completed work on the `EntityUpdateMixin`. As a bonus, I've revamped and expanded the tests in module `tests.test_entity_mixins`. I'm now adding a second commit to that branch which expands the documentation a bit. What needs to be done before I submitt a PR that will close this issue?

* Finish expanding the documentation.
* Test the final result. Update Robottelo with a few tests that make use of the new `EntityUpdateMixin` and make sure everything's sane.
* Get #106 merged.
