### ISSUE TITLE
Add RepositorySet entity

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#126]
See #122 for context on why a `RepositorySet` entity is desirable. In short:

* Repository sets are listed in the API docs.
* It would be nice to replace `Product.repository_sets_available_repositories` with `RepositorySet.available_repositories`. The latter makes much more sense.

**Comment by elyezer** [comment]
:+1:

**Comment by oshtaier** [comment]
Already implemented
