### ISSUE TITLE
Make `read`'s `ignore` argument easier to manipulate

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#134]
The `read` method has this signature:

```python
def read(self, entity=None, attrs=None, ignore=()):
```

The `ignore` argument is a tuple of field names that NailGun should not try to populate when reading data from the server. For example, this is the signature of `DockerComputeResource.read`:

```python
def read(self, entity=None, attrs=None, ignore=('password',)):
```

This method signature works well if one wants to ignore a certain method attribute at all times. However, this method signature does not work well if one wants to conditionally ignore some field due to a bug. For example, this bit of code is used in response to a specific bug:

```python
ignore = set(ignore).union([…])  # list comprehension
if 'errata_id' in attrs:
    ignore.discard('errata')  # pylint:disable=no-member
ignore = tuple(ignore)
```

In the above code snippet, `ignore` is converted to a set, manipulated, then converted back to a tuple. Unwieldy idioms like this are likely to become more prevalent as more field-specific bugs are discovered - especially when those bugs are fixed in certain Satellite versions.

An empty tuple is used as the default argument to `read` because:

* tuples are immutable
* the field should default to an empty iterable

However, as described above, tuples are hard to work with. Some better solution should be conceived and implemented.

One alternative it to make `read` have this signature:

```python
def read(self, entity=None, attrs=None, ignore=None):
```

And somewhere in the call stack, `ignore` would be given a default value:

```python
if ignore is None:
    ignore = set()
```

This would work decently well in cases where an argument should always be ignored:

```python
def read(self, entity=None, attrs=None, ignore=None):
    if ignore is None:
        ignore = set()
    ignore.add('password')
```

It would also work very well in cases where more interesting manipulations need to happen:

```python
ignore.add([…])  # list comprehension
if 'errata_id' in attrs:
    ignore.discard('errata')  # pylint:disable=no-member
```

This solution would retain the two advantages listed earlier:

* <del>tuples are</del><ins>None is</ins> immutable
* the field should default to an empty iterable

**Comment by elyezer** [comment]
```python
>>> s = set()
>>> s.add([1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

You mean `[ignore.add(elem) for elem in items]` on the list comprehension lines? The only disadvantage I see here is that add should be called for every item that should be ignored, but it looks the right data type to use because repeating field names will not make any sense.

**Comment by Ichimonji10** [comment]
@elyezer I used the wrong method. There's three methods that can be used to combine elements together, and they all work a little bit differently:

```python
>>> s = set()
>>> s.add(1)
>>> s.update([2, 3, 4])
>>> s.union([4, 5, 6])
{1, 2, 3, 4, 5, 6}
>>> s
{1, 2, 3, 4}
```

I should have used `update` in my example:

```python
ignore.update([…])  # list comprehension
if 'errata_id' in attrs:
    ignore.discard('errata')  # pylint:disable=no-member
```

**Comment by elyezer** [comment]
@Ichimonji10 oh I see. Was late yesterday and I did not realize about the update method... With this method now it looks even better.

**Comment by elyezer** [comment]
:+1:
