### ISSUE TITLE
Remove "null" from fields and entities

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#135]
The base `Field` class has the following signature:

```python
    def __init__(
            self,
            required=False,
            choices=None,
            default=_SENTINEL,
            null=False):
```

The "required", "choices" and "default" attributes are all used when generating random data for testing purposes. However, the "null" attribute is not used at all, anywhere, to the best of my knowledge. This is silly. Why should a completely useless attribute be bumming around?

Drop the `null` attribute. Doing so will not affect anything right now, given that there is no usage of the field. It should be done before version 1.0 is released, as dropping the attribute is a backward-incomptable change. (Some client may reference the attribute.) In addition, the attribute can be added again after version 1.0 is released without breaking anything - only prompting a minor version number bump.

**Comment by elyezer** [comment]
The initial `null` usage was to mark fields that can receive null as a value. This can be used in some validation or when generating random data. There is no other usage than the mentioned ones and I don't have a point to say that they should continue there. With that said, I agree that it can be dropped.
