### ISSUE TITLE
Handle backward compatibility

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#136]
NailGun generally tries to keep up with new versions of Satellite as they are released. This is great for developers and those running the current version of Sat, but it's terrible for anyone running an older version of Satellite. It would be great if there was some mechanism by which we could check to make sure that NailGun is not breaking compatibility with older versions of Satellite. This is already somewhat feasible: NailGun has the ability to store a version in its `ServerConfig` objects, and those version numbers are used to conditionally execute several work-arounds.

If each new release of NailGun breaks compatibility with old versions of Satellite, then release numbers are essentially meaningless. We should either come up with some system for checking for backward compatibility, or we should come up with a statement saying which versions are supported by a given NailGun version.

**Comment by elyezer** [comment]
What about creating a test script, something like configure? Then we can create a jenkins job to run the script against some satellite versions.

I don't see any other option without the need of running NailGun against a real Satellite 6 server. But I think worth checking the json file generated and check if it can help in some way. This way we can store the json and make travis run.

**Comment by Ichimonji10** [comment]
Running a check against the JSON file is a good start. Doing so would also give us a decent metric for how "complete" NailGun is at any given point in time.

**Comment by elyezer** [comment]
python-foreman stores the information for just foreman https://github.com/david-caro/python-foreman/tree/master/foreman/definitions. We need to do the same but using the Satellite 6 API (which have more endpoints).

**Comment by Ichimonji10** [comment]
I agree that we should only grab the info for the v2 API. We've never targeted v1, so that information would just be cruft.

**Comment by Ichimonji10** [comment]
It may be possible to address this issue by fixing #214.
