### ISSUE TITLE
Documentation not being generated

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#141]
Documentation is not being generated on Read The Docs. The relevant error looks like this:

      File "conf.py", line 10, in <module>
        from pkg_resources import SetuptoolsVersion
    ImportError: cannot import name SetuptoolsVersion

`pkg_resources.SetuptoolsVersion` is provided by the `setuptools` package, which NailGun lists as a dependency. The problem is that RTD downgrades the installed setuptools version from 0.16.0 to 1.1.

    Downloading/unpacking setuptools==1.1

Newer versions of setuptools, such as 0.16 (installed by default before the downgrade) and 0.18 (the latest) do provide the `SetuptoolsVersion` class.

There are two possible solutions I see:

* Specify a minimum required `setuptools` version. This may or may not fix the issue, depending upon whether the downgrade happens before or after NailGun's dependencies are installed.
* Drop `setuptools` as a dependency and use `packaging` instead. The `packaging` package is provided by the Python Packaging Authority, and it's used under the hood by setuptools. Its `packaging.version.Version` class and `packaging.version.parse` function would serve the same role as the `SetuptoolsVersion` class and `parse_version` functions, respectively. This option is mainly attractive because it's more targeted than setuptools, which provdes boatloads of functionality we don't need.

**Comment by elyezer** [comment]
The second option to use packaging package seems to be better to me.

**Comment by Ichimonji10** [comment]
RTD is sucessfully building documentation again. After looking through the build log, I see that setuptools 18.0.1 is now being used, which is the current version of the lib.
