### ISSUE TITLE
Support Multiple API versions

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#15]
Make it possible to interact with multiple versions of the Satellite API using NailGun. Currently, NailGun targets the most up-to-date version of the Satellite API at all times. The mechanism for supporting this is unclear. Simply creating a new git branch for each version of the Satellite API is a bad idea. Many commits would have to be cherry-picked from master to other branches and numerous similar packages would need to be uploaded to PyPi, all of which is error-prone and labor-intensive. A better mechanism would be to set an element in the config file or at run-time that sets the target API version. How to support this is unclear.

**Comment by Ichimonji10** [comment]
One idea I've considered is to add a `version` attribute to the `ServerConfig` class. The attribute would contain a value like this:

    ('foreman', '1.7.0')

You could then use `__new__` to customize classes when instances are being created:

```python
class MyEntity(Entity):
    def __new__(cls, server_config=None, **kwargs):
        if server_config.version == ('foreman', '1.7.0'):
            cls.attr = entity_fields.StringField()
        return super(MyEntity, self).__new__(cls, server_config, **kwargs)
```

However, this fails for the simple reason that touching `cls` affects `MyClass`. (Duh…) For example:

```python
>>> class Foo(object):
...   def __new__(cls):
...     cls.bar = 1
...
>>> hasattr(Foo, 'bar')
False
>>> Foo()
>>> hasattr(Foo, 'bar')
True
```

And this would mean that the very definition of `MyClass` is unstable. Why is this an issue? It's an issue because certain classes make use of class attributes when they do their work. For example, here is a snippet from [create_payload](http://nailgun.readthedocs.org/en/latest/api/nailgun.html#nailgun.entity_mixins.EntityCreateMixin.create_payload):

```python
        data = self.get_values().copy()
        api_names = getattr(self.Meta, 'api_names', {})
        for field_name, field in type(self).get_fields().items():
            if field_name in data:
                # mangle `field_name` so that our `field_name`
                # matches what the server expects.
        return data
```

Notice the call to `type`:

    for field_name, field in type(self).get_fields().items():

The class definition is used when determining what data is sent to the server. And if the very definition of the class changes, then the data that is sent to the server will vary over time. Ergh.

**Comment by Ichimonji10** [comment]
One solution is adding a version specifier to the `Field` class:

```python
class Employee(Entity):
    name = StringField()
    title = StringField(version=('foreman', '>=', '1.7.0'))
```

I don't like this solution very much, though. I see at least one big problem. The version specifier above is only capable of expressing the statement "this field exists in foreman version 1.7.0 and above." There may be other versioning differences, though. For example, what if you wanted to express the statement "this field has a minimum length of three characters in foreman version 1.7.0 and above." You cannot express that information with the above design.

**Comment by Ichimonji10** [comment]
A second solution is to completely abandon class attributes. Class attributes work well when a single, unchanging definition is to be used globally by the Python interpreter. However, if this issue is to be solved successfully, then that will no longer be the case. If this issue is to be solved, then something like this should be possible:

```python
>>> hasattr(
...     Product(ServerConfig('http://old_sat.example.com', version='6.0')),
...     'sync_plan'
... )
False
>>> hasattr(
...     Product(ServerConfig('http://new_sat.example.com', version='6.1')),
...     'sync_plan'
... )
True
```

This could be made to work by moving field definitions in to the `__init__` method:

```python
class Product(Entity):
    def __init__(self, server_config, **kwargs):
        self._fields = {
            'description': entity_fields.StringField(),
            'label': entity_fields.StringField(),
            'name': entity_fields.StringField(required=True),
            'organization': entity_fields.OneToOneField(Organization, required=True),
            'sync_plan': entity_fields.OneToOneField(SyncPlan, null=True),
        }
        if server_config.version >= '6.1':
            self._fields['gpg_key'] = entity_fields.OneToOneField(GPGKey)
        super(Product, self).__init__(server_config, **kwargs)
```

There is at least one *very* nice side-effect of this approach. Currently, the entities contain lines such as the following:

    gpg_key = entity_fields.OneToOneField('GPGKey')

Using instance attributes allows us to name classes directly:

    'gpg_key': entity_fields.OneToOneField(GPGKey)

Naming classes directly would allow us to drop fragile stuff like `nailgun.entity_fields.ENTITIES_MODULE` and `nailgun.entity_fields._get_class`. (As I write this, I've just noticed a bug! The `ENTITIES_MODULE` variable is re-defined in module `nailgun.entities`. The bug is benign, as the variable is not changed. But still. This is subtle and could cause trouble.)

**Comment by Ichimonji10** [comment]
The [entity-fields branch](https://github.com/SatelliteQE/nailgun/compare/entity-fields) adds support for this feature. The second commit message provides a brief example of the power of the feature. If anyone is interested, please do take a look. Even better, try checking the branch out and try using it.

I will likely submit that branch for review tomorrow. The set of changes is significant enough that I'd like more eyes on the branch. (I'm going to wait until tomorrow to do so because I've had a limited ability to test the changes against live machines thus far, and I don't want to waste people's time. Hopefully the situation will be improved tomorrow.)

**Comment by omaciel** [comment]
Awesome!!! As you can see, version ``6.0.8`` does not have the fields ``checksum_type`` and ``docker_upstream_name`` but version ``6.1`` does.

```python
In [1]: from pprint import pprint

In [2]: from nailgun.config import ServerConfig

In [3]: from nailgun.entities import Repository

In [4]: sat_60 = ServerConfig.get('example')

In [5]: sat_61 = ServerConfig.get('default')

In [6]: for server in [sat_60, sat_61]:
   ...:     pprint (server.version)
   ...:     pprint (Repository(server).get_fields())
   ...:
<Version('6.0.8')>
{'content_type': <nailgun.entity_fields.StringField object at 0x110b09d50>,
 'gpg_key': <nailgun.entity_fields.OneToOneField object at 0x110b22110>,
 'id': <nailgun.entity_fields.IntegerField object at 0x110b09d10>,
 'label': <nailgun.entity_fields.StringField object at 0x110b22190>,
 'name': <nailgun.entity_fields.StringField object at 0x110b221d0>,
 'product': <nailgun.entity_fields.OneToOneField object at 0x110b22210>,
 'unprotected': <nailgun.entity_fields.BooleanField object at 0x110b22290>,
 'url': <nailgun.entity_fields.URLField object at 0x110b22510>}
<Version('6.1')>
{'checksum_type': <nailgun.entity_fields.StringField object at 0x110b09d50>,
 'content_type': <nailgun.entity_fields.StringField object at 0x110b09c10>,
 'docker_upstream_name': <nailgun.entity_fields.StringField object at 0x110b09f10>,
 'gpg_key': <nailgun.entity_fields.OneToOneField object at 0x110b22290>,
 'id': <nailgun.entity_fields.IntegerField object at 0x110b22310>,
 'label': <nailgun.entity_fields.StringField object at 0x110b22190>,
 'name': <nailgun.entity_fields.StringField object at 0x110b22510>,
 'product': <nailgun.entity_fields.OneToOneField object at 0x110b221d0>,
 'unprotected': <nailgun.entity_fields.BooleanField object at 0x110b22110>,
 'url': <nailgun.entity_fields.URLField object at 0x110b22210>}
```

**Comment by Ichimonji10** [comment]
The solution I've adopted for fixing this bug is a breaking change. Prior to the fix, fields are public class attributes. After the fix, fields are values in the private instance attribute `_fields`. As a result, I'm marking this bug as a breaking change.
