### ISSUE TITLE
Single Version Number

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#17]
There should be a single, authoritative source for the current version of NailGun. The version number <del>will be</del> <ins>is</ins> declared in the following locations <del>once the commits in the "bootstrap" branch are merged in to master</del>:

* `setup.py`
* `docs/conf.py`

That's not great. It's easy to update one and forget about the other. The ["Single-sourcing the version across `setup.py` and your project"](https://packaging.python.org/en/latest/development.html#single-sourcing-the-version-across-setup-py-and-your-project) section of the Python Packaging User Guide provides some suggestions.

**Comment by Ichimonji10** [comment]
One solution is to maintain a version number in `nailgun/__init__.py`. You could access it like this:

```python
>>> from nailgun import VERSION
>>> 'VERSION'
'1.2.3'
```

This could be very useful for two reasons:

* Client code could inspect the version number directly. [1]
* NailGun itself could use this version number for forward/backward compatibility purposes. For example, let's say that the `ServerConfig` object changes and the contents that are dumped out to a configuration file (e.g. `~/.config/nailgun/server_config.json`) change. NailGun might be able to deal with this better if it's able to inspect its own version number and therefore do clever things like have multiple configuration files (e.g. `~/.config/nailgun/server_config_1.2.3.json` `~/.config/nailgun/server_config_2.3.4.json`).

[1] Goodness knows we've had enough issues trying to determine what version Satellite is when testing and troubleshooting - I don't want to make NailGun clients face the same issues. By a similar token, though, it's easy to determine what version NailGun is by asking pip or the system package manager. Sat is a different beast.

**Comment by Ichimonji10** [comment]
The second point above about versioned configuration files could actually be a very good use case for a version number. I don't know if it's the totally right way to do things, but at the very least, it's a use case that would affect NailGun's forward compatibility. This issue should at least be *considered* (though not necessarily resolved) before version 1 is released.

**Comment by elyezer** [comment]
A common practice I saw in some projects, is having the version in the package root `__init__.py` file. Like requests package [1], but it have to run some logic [2] to get the version number without importing the package, this is important because importing the package may raise an exception if some dependency is not already installed (like in a new environment). Django does the same thing [3] and it ensures that the version is PEP 386 [4] compliant.

I think we should consider those points because the projects are around for a good time and many developers have touched them. With that said, I think having the version in the `__version__` and being a PEP 386 compliant is a good way to go.

[1] https://github.com/kennethreitz/requests/blob/master/requests/__init__.py#L45

[2] https://github.com/kennethreitz/requests/blob/master/setup.py#L31

[3] https://github.com/django/django/blob/master/django/__init__.py#L5

[4] https://www.python.org/dev/peps/pep-0386/

**Comment by Ichimonji10** [comment]
@elyezer Thanks for the links. That's some good reading.

I read through both [PEP 386](https://www.python.org/dev/peps/pep-0386/) and [PEP 440](https://www.python.org/dev/peps/pep-0440/). The latter supercedes the former and, while mostly compatible, smoothes out some rough edges. For example, leading and trailing whitespace are no longer allowed, version epochs are added (yay!) and single digit version numbers are allowed. It's also *mostly* compatible with semantic versioning.

It's good to know that it's possible to extract a version number without properly importing a module. That means that we can start with a normal import and add string parsing logic at a later point if so desired.

All that said, I still don't see any use case that is well served by placing the version number in the root `__init__.py` file:

* If Python code wants to programmatically access a version number, it can do `from pkg_resources import get_distribution; get_distribution('package_name').version`.
* If there is a need to version underlying resources, such as the `server_config.json` file, that can be done without referencing the version number. IMO, *not* referencing the software version number promotes good software layering.
* Adding a version in to the root `__init__.py` file risks import issues as time goes on.

I like solution 4 in [Single-sourcing the Project Version](https://packaging.python.org/en/latest/single_source_version.html):

> Place the value in a simple `VERSION` text file and have both `setup.py` and the project code read it.
>
> ```python
> with open(os.path.join(mypackage_root_dir, 'VERSION')) as version_file:
>     version = version_file.read().strip()
> ```
>
> An advantage with this technique is that it’s not specific to Python. Any tool can read the version.

It's simple, tool-agnostic and forward-compatible with adding a version to the root `__init__.py` file.

**Comment by omaciel** [comment]
:+1: to `tool-agnostic and forward-compatible` solutions :)

**Comment by elyezer** [comment]
Cool stuff, +1 on storing the version on VERSION file.

**Comment by Ichimonji10** [comment]
Awesome. Sounds like we have a solution.
