### ISSUE TITLE
Create a config file

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#2]
Certain information that was available in Robottelo must also be available in NailGun. For example, user credentials and the server hostname must be available. In Robottelo, this information is available via the robottelo.properties file (see robottelo.properties.sample). A good strategy might be to give NailGun its own settings file which has the same syntax as that use by Robotteo. In that case, NailGun can either operate stand-alone, or NailGun's settings file can be symlinked to Robottelo's config file.

**Comment by Ichimonji10** [comment]
Thank you for the feedback, @elyezer. I really do appreciate it. :)

I've finally written up a configuration module. See [here](https://github.com/SatelliteQE/nailgun/compare/config). The code may look a bit weird if you dive straight in to the source material, so let me start off with an example of how one might use the new module:

```python
>>> from nailgun.config import ServerConfig
>>> ServerConfig(
...     'http://example.com:250',
...     auth=('Alice', 'hackme'),
...     verify=False
... ).save()
>>> ServerConfig('https://example.org').save('secondary')
>>> ServerConfig.get_labels()
(u'default', u'secondary')
>>> sc = ServerConfig.get()
>>> del sc.verify
>>> vars(sc)
{'url': u'http://example.com:250', 'auth': [u'Alice', u'hackme']}
>>> sc.save()
```

Notice how the `save` and `get` methods default to operating on a config named "default". This makes it very easy to manage a single server's connection info, yet also allows for multi-server setups.

The `ServerConfig` class has several other methods that are not demonstrated here. You can imagine what the `delete` method does. The `get_client_kwargs` method is a little less obvious:

```python
>>> from nailgun import client, config
>>> sc = config.ServerConfig(
...     'http://example.com:250',
...     auth=('Alice', 'hackme'),
...     verify=False
... )
>>> sc.get_client_kwargs()
{'verify': False, 'auth': ('Alice', 'hackme')}
>>> response = client.get(sc.url + '/api/v2', **sc.get_client_kwargs())
```

OK, so that's _how_ it works. There are a lot of interesting implementation notes, though. In no particular order:

* The configuration file can theoretically be saved in any number of formats. For example, it could be a SQLite database, a pickled dump of data, JSON, INI or plain Python code. (@elyezer) I chose not to use Python code because Python files are best suited to being read-only information stores. It's really hard to write out to Python files. INI was dropped because working with such files is kludgy: non-string data types are either hard or impossible to store (lists! augh!), they are case-insensitive by default, they lose the ability to represent certain characters like leading whitespace, and so on. A SQLite database seems like overkill and is not human-editable. A pickled dump of data is tempting due to its ability to natively store nearly any object type (and `nailgun.client` can authenticate using exotic objects like [`HTTPDigestAuth`](http://docs.python-requests.org/en/latest/user/authentication/#digest-authentication), but it is again not human-readable, and so far Satellite does not seem to support such. JSON is human-editable, machine-editable, has a nice interface, supports all the common data types, and has good mindshare. (No DSLs, please.)
* `nailgun.config` does not support interfacing with Robottelo configuration files in any way. I think this is a good design choice, though. NailGun is a toolkit that is supposed to have knowledge of Satellite, but not its users. NailGun is supposed to sit here: `??? → NailGun → Satellite`. I don't want to break that nice layering of responsibilities. Instead, Satellite (and any other users of NailGun) can provide NailGun with information has necessary by creating and populating `ServerConfig` objects.
* Using double-stars (e.g. `**sc.get_client_kwargs()`) is a bit distasteful to me, but it's *really* useful. It's _so_ useful that I'm just going with it.
* The `ServerConfig` class has only one required attribute (`url`) and two optional ones (`auth` and `verify`). That's it. I've considered adding a mechanism for adding arbitrary attributes to a ServerConfig object (e.g. `headers`) but have decided against that. NailGun exists, in part, to make assumptions for you. We know that the content-type of requests is `application/json` in most cases (except when uploading files), and have baked that logic into `nailgun.client`. We know that the `auth`, `verify` and `url` options are the only three options to be used in most requests, so I've baked that knowledge into the `ServerConfig` class. And we know that for certain types of requests, other information must be passed in via e.g. the `data` argument. And for those requests, the methods on the `entities` classes suffice.
* The `ServerConfig` object is designed to interface nicely with the `entities` classes. Currently, the `entities` classes accept an optional `auth` parameter. When porting the entities over to NailGun, I'm going to drop that argument and instead add a `server_config` argument. The idea is that the default server configuration will be fetched if none is provided, or an anonymous `ServerConfig` object may be passed in. Sweet. This means that unusual, one-off server configurations can be used without polluting the global configuration file.

**Comment by elyezer** [comment]
@Ichimonji10 thanks for the in deep explanation. The module looks great.

I agree with your points, and remember that we can aways improve later, even though we have a good start here.
