### ISSUE TITLE
Method _poll_task needs to check if task has started running

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/nailgun#222]
Several of our automated tests have show that synchronization and publishing tasks are being polled only once and immediately failing with a `TaskFailedError` exception.

The problem seems to be related to how `_poll_task` only polls a task if its state is `running`. If the state is **not** `running` then we check for the final result, and if `result != 'success' we raise the exception.

Turns out that we have some tasks triggered by the automation that sit on the `planned` state for a while and since `'planned' != 'running'` we get out of the loop and stop polling right after the first check.

Based on the [source code](https://github.com/Dynflow/dynflow/blob/e9c02b60b26e4a8636c85b5d51192d468430d2f7/lib/dynflow/execution_plan.rb#L23) from *TheForeman*, a task can go through the following state transitions:

```ruby
    def self.state_transitions
      @state_transitions ||= { pending:  [:stopped, :scheduled, :planning],
                               scheduled: [:planning, :stopped],
                               planning: [:planned, :stopped],
                               planned:  [:running],
                               running:  [:paused, :stopped],
                               paused:   [:running],
                               stopped:  [] }
    end
```

So I believe that we need to make sure that when polling a task the following states should be observed before either exiting the loop or timing out: `scheduled`, `planning`, `planned` and `running`

An example of a failed test shows (snip):

```json
{"id":"97caeb65-60f1-44df-b482-1d244bb3412d",
"label":"Actions::Katello::Repository::Sync",
"pending":true,
"username":"admin",
"started_at":"2015-09-21T00:56:32Z",
"ended_at":null,
"state":"planned",
"result":"pending",
"progress":0.0,
"input":{"repository":{
"id":9,
"name":"쒲10𣊈쾹10𣊈𩶴麣10𣊈𩶴𨃉䧠惋10𣊈𩶴𨃉𧵷10𣊈𩶴𨃉𧵷𪥚10𣊈𩶴𨃉𧵷𪥚𪚑쾚낕",
"label":"4b6fa137-86c7-427b-b56f-d6078d03c69a"},
"product":{"id":3,"name":"10𣊈𩶴𨃉𧵷𪥚𪚑𩙉䧊10𣊈𩶴𨃉𧵷𪥚𪚑𩙉𩏞",
"label":"7eb07dfd-3dde-4c0d-92a5-ee10619929cb","cp_id":"1442796989475"}
```

**Comment by omaciel** [comment]
Perhaps the logic should be applied to exiting the loop if state is `paused` or `stopped`?

**Comment by sthirugn** [comment]
@omaciel:   :+1: yes we can break the loop on paused/stopped.
