### ISSUE TITLE
make compatible with current pylint version

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#247]
Current versions of Pylint throw errors when run over the NailGun codebase, as described in #246. Let's make NailGun compatible with the current version of Pylint and/or work with the Pylint developers to fix any possible regressions in the tool.

**Comment by renzon** [comment]
I am closing this issue once it seems we already have made that change, including dropping support do Python < 2.7: https://github.com/SatelliteQE/nailgun/blob/master/.travis.yml#L4
