### ISSUE TITLE
Support Usergroup as a value for entities.Host.owner field

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/nailgun#258]
Right now the `owner` field for Host entity is defined as
`'owner': entity_fields.OneToOneField(User),`
The issue here is `owner` depends on `owner_type` field, which can be one of 'User' or 'Usergroup'.
In case `owner_type == 'Usergroup`, the host can't be read/created, as nailgun will search for user, not for Usergroup.

**Comment by abalakh** [comment]
Off the top of my head we can try to define the `owner` field like this:
```python
            'owner': entity_fields.OneToOneField(
                UserGroup if kwargs.get('owner_type') == 'Usergroup' else User
            ),
```
Update the Host.read() as following:
```python
    def read(self, entity=None, attrs=None, ignore=None):
        ...
        if entity is None:
            entity = type(self)(
                self._server_config, owner_type=attrs.get('owner_type'))
        return super(Host, self).read(entity, attrs, ignore)
```
And then it will be possible to work with usergroups in tests like this:
```python
        host = entities.Host(owner_type='Usergroup')
        del host.owner_type
        host.create_missing()
        usergroup = entities.UserGroup(
            role=[role],
            user=[user],
        ).create()
        host.owner_type = 'Usergroup'
        host.owner = usergroup
        host = host.create(create_missing=False)
```
2 drawbacks here:
- It's a bit ugly to define `owner_type` each time for each instance of Host
- (not sure) Because Host.create_missing() doesn't work with any class attributes, you need to define `owner_type` for instance of Host, then delete it, then call `create_missing()`, then define `owner_type` once again. That's not cool at all, but it more like `create_missing()` method issue for me and can be easily resolved.

Any suggestions?

**Comment by Ichimonji10** [comment]
How about declaring a [property](https://docs.python.org/3.5/library/functions.html?highlight=property#property) called `owner_type`? Whenever the `owner_type` instance attribute is set, the property can step in and set both `owner` too. I think the usage would look like this:

```python
host = entities.Host()
host.owner_type = 'User'  # property intercepts call, sets `owner` too
host.owner_type = 'Usergroup`  # same here
```

**Comment by abalakh** [comment]
Thanks for advice! Was playing with properties today, here's what i've came up with:
[https://gist.github.com/abalakh/dc0db72b7ffc4d0222bb](https://gist.github.com/abalakh/dc0db72b7ffc4d0222bb)
Had to implement custom `get_values()`, as `vars(self)` can't show the property, it shows private variable instead.
I thought it was already a working solution, as i tried to test it with some pre-defined values like this:
```python
host = entities.Host(
            location=1,
            organization=1,
            owner=3,
            owner_type='Usergroup',
).create()
```
and it was working ok, but when i set `owner=` to a Usergroup enitity - no success.
The reason is following:
When we initialize new Host() instance, we have `self._fields['owner']` set to `OneToOneField(User)` by default. When it comes to populating the instance with values provided as arguments, in `Entity.__init__()` we're going through all the arguments provided. Unfortunately, `owner` comes before `owner_type`.
That means we have `owner == entity.UserGroup()`, but `self._fields['owner'] == entity.User()`.
As a result, in `Entity.__init__()` we call for `_make_entity_from_id()` to receive an entity with its id. And that function checks, if the same entity as in `self._fields` declaration was provided. If so - it fetches the id, otherwise it assumes that probably id, not the entity was provided and just sets provided value to id field.
So we're recieving `entities.Host().owner` set to `entities.User` instance (not `entities.Usergroup` as we're expecting), and even more - that `owner.id` is not integer value, but another entity - `entities.Usergroup` :smile: 
Any ideas on how to avoid that?

**Comment by abalakh** [comment]
Actually i can try to update `Host.get_values()` with something like this:
```python
    def get_values(self):
        """Replace ``_owner_type`` with ``owner_type``"""
        attrs = super(Host, self).get_values()
        attrs['owner_type'] = attrs.pop('_owner_type')
        if (
                attrs.get('owner') and
                hasattr(attrs['owner'], 'id') and
                (isinstance(attrs['owner'].id, User) or
                 isinstance(attrs['owner'].id, UserGroup))):
            attrs['owner'] = attrs['owner'].id
        return attrs
```
But that looks so wrong to me. Looks like i'm fighting with consequences, not the cause
