### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#26]
NailGun's documentation is lacking. Most prominently, the "examples" section tells how to write some requests to the API without NailGun, but not with it! That said, the entire set of documentation could use a read-through to make sure it's well structured and touches on the right topics.

**Comment by elyezer** [comment]
:+1:

**Comment by Ichimonji10** [comment]
The "docs" branch contains my current attempt at addressing this issue. See [here](https://github.com/SatelliteQE/nailgun/compare/docs).
