### ISSUE TITLE
Move code from Robottelo to NailGun

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#3]
The starting code for NailGun will come from Robottelo. Most importantly, the [`robottelo/entities.py`](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/entities.py) module must be ported. As a consequence, dependencies must also be either moved over or otherwise satisfied. This includes the `robottelo/orm.py` module, the `bz_bug_is_open` function from `robottelo/common/decorators.py` and the `get_server_credentials` function from `robottelo/common/helpers.py`.

**Comment by Ichimonji10** [comment]
A config parser has been put together, and an initial implementation of it was accepted in #21. It turns out that the config parser may be useful for other applications, such as StapleGun. As a result, I have reworked the config parser somewhat. You can see my changes in [this branch comparison](https://github.com/SatelliteQE/nailgun/compare/base-config). I am going to re-work the commit messages for those changes, and then will submit a pull request. At that point, a new release of NailGun will likely be put out.

**Comment by elyezer** [comment]
Will you reuse the base config class on Staple Gun? Or it will have its own copy?

**Comment by Ichimonji10** [comment]
@elyezer, in the immediate future, I think StapleGun will list NailGun as a dependency and import the `BaseServerConfig` class. I don't think there's any technical reason that the `BaseServerConfig` class should be copied. Going forward, we may split out the `BaseServerConfig` and `ConfigFileError` classes into a separate package.

**Comment by elyezer** [comment]
@Ichimonji10 agreed. I was thinking on a separated package, but if it will list NailGun as requirement then import from NailGun should be the better approach at first.

**Comment by Ichimonji10** [comment]
@elyezer, I agree. I'd like to make a separate package, but for now, I'm OK with other libs importing `nailgun.config.*`.

By the way, there are some other hunks of code that could be moved from Robottelo into a separate package. For example, [`bz_bug_is_open`](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/common/decorators.py#L287) and `rm_bug_is_open` could be moved into a separate package. This would be good because `ActivationKey.read_raw` depends on that function, the `ActivationKey` is going to be moved to NailGun, and the dependency tree would be much more sane if `rm_bug_is_open` is moved:

    Robottelo
    ├── nailgun
    └── staplegun
        └── librobottelo (?)

**Comment by elyezer** [comment]
@Ichimonji10 definitely, I also see uses for the bz related functions to automation-tools. For example only do a workaround if a bug is open.

**Comment by omaciel** [comment]
@Ichimonji10 @elyezer we now find ourselves at an interesting point and I'm more than willing to factor things out to make code easily used by other projects :) Why don't we create a new project to hold the code that let's us check bugzilla/redmine and factor it out?

**Comment by omaciel** [comment]
New project's names:
* B00ger :)
* Bugger
* Bugzinga

**Comment by elyezer** [comment]
@omaciel I'm +1 on that.

Name suggestion beetlejuice :smile:

**Comment by omaciel** [comment]
Nom nom

**Comment by omaciel** [comment]
* BugBot

**Comment by omaciel** [comment]
* Bugnore

**Comment by elyezer** [comment]
* BugSkipper

**Comment by omaciel** [comment]
* Bugaboo :)

**Comment by omaciel** [comment]
* abugado (sounds like Lawyer in Spanish hehe)

**Comment by omaciel** [comment]
* de**bug**s (ok, ok, I'm done now)

**Comment by omaciel** [comment]
* hum**bug** (I lied hehe)

**Comment by cswiii** [comment]
jungleb00gie
