### ISSUE TITLE
Need to make nailgun.entity.HostCollection searchable.

### ISSUE THREAD

**Issue by nstrug** [SatelliteQE/nailgun#307]
Currently, nailgun.entities.HostCollection does not implement nailgun.entity_mixins.EntitySearchMixin.

This makes it impossible to simply search for a specific HostCollection.

This is currently hampering efforts in SOE-CI which require this functionality - specifically to reimplement the following in python+Nailgun: https://github.com/RedHatSatellite/soe-ci/blob/master/common.sh#L39

**Comment by nstrug** [comment]
I think there's more to this then simply making HostCollection searchable.
HostCollection.host, which should contain a list of all the hosts assigned to the host collection, doesn't seem to even be populated.

**Comment by rochacbruno** [comment]
@nstrug thanks for pointing that, I opened #310 as separated issue to cover `HostCollection.host` populate problem.
