### ISSUE TITLE
HostCollection.host is not being populated

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/nailgun#310]
As pointed out by @nstrug  here:https://github.com/SatelliteQE/nailgun/issues/307#issuecomment-240991564

> HostCollection.host, which should contain a list of all the hosts assigned to the host collection, doesn't seem to even be populated

**Comment by rochacbruno** [comment]
@nstrug there is a BZ opened https://bugzilla.redhat.com/show_bug.cgi?id=1325989

Currently `.hosts` fields is not returned by the server.

**Comment by abalakh** [comment]
@rochacbruno exactly. btw, this issue is tracked as a part of #270. Not sure if we need a separate one

**Comment by rochacbruno** [comment]
Fixed in #314
