### ISSUE TITLE
Make entities JSON Serializable

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/nailgun#323]
in #321 @ehelms discovered that nailgun entities are not JSONSerializable.

I made a simple test.

``` python
In [1]: from nailgun.entities import Organization
In [2]: org = Organization()
In [3]: import json
In [4]: json.dumps(org)
/usr/lib64/python2.7/json/encoder.pyc in default(self, o)
    182 
    183         """
--> 184         raise TypeError(repr(o) + " is not JSON serializable")
    185 
    186     def encode(self, o):

TypeError: Organization(nailgun.config.ServerConfig(....)) is not JSON serializable
```

That happens because `__repr__` of entities are not returning values that default JSON Decoder is able to parse, also there is no `to_json` method and no recursive traversing of nested entities.

We can develop all of this builtin, but looks like a lot of work, so:

I am suggesting to use Marshmallow[1] as it is a known and stable existing library to give  Schema Validation and Serialization to nailgun.

[1] https://marshmallow.readthedocs.io/en/latest/

If including one more external dependency is a problem we can start developing builtin functionality.

NOTES:
1. That feature looks important in order to make **nailgun** working out of the box with Ansible
2. We can make it in the way the method `to_json` needs to be explicitly called or provide `nailgun.JSONDecoder` to be used when dumping or try to automate everything.
3. It can be implemented as a `nailgun_plugin` so a different project `pip install nailgun-json` and when that thing is installed `json.dumps(entity)` will automatically give a json relying on Marshmallow.

**Comment by JacobCallahan** [comment]
this might be me having some ulterior motives (being able to see all class parameters without instantiation), but I've become quite fond of the attrs library (https://pypi.python.org/pypi/attrs). It comes with some very amazing built-in functionality (repr, slots, cmp, hash, assoc) and when combined with the json module we can do things like this.
```
In [46]: @attr.s()
    ...: class TestClass(object):
    ...:     a_param = attr.ib()
    ...:     b_param = attr.ib()
    ...:     c_param = attr.ib()
    ...:     d_param = attr.ib()
    ...:     def to_json(self):
    ...:         return json.dumps(attr.asdict(self))
    ...:     
In [47]: myclass = TestClass(1, 'b', ['c'], ('d', 4))
In [48]: myclass.to_json()
Out[48]: '{"c_param": ["c"], "d_param": ["d", 4], "b_param": "b", "a_param": 1}'
```
Not sure if it will fix the issues of json serialize-able attributes, but you can also turn off attributes you don't want to be included in the repr.
```a_param = attr.ib(repr=False)```

**Comment by JacobCallahan** [comment]
btw, this is what I was talking about for inspecting class fields without instantiation.
```
In [51]: attr.fields(TestClass)
Out[51]: 
(Attribute(name='a_param', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=True, convert=None),
 Attribute(name='b_param', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=True, convert=None),
 Attribute(name='c_param', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=True, convert=None),
 Attribute(name='d_param', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=True, convert=None))
```

**Comment by elyezer** [comment]
NailGun already converts data to a JSON serialize format check https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L151-L183. Maybe we can take advantage of that and create a mixin that will provide the `to_json()`.

I am not sure if that will help on making NailGun compatible with Ansible but is a solution to consider. Using another lib like marshmallow or attrs seem to me a lot of work since will need to update the fields to their fields, but I am maybe missing something.

My view is that NailGun can provide it with the tools it already has.

**Comment by JacobCallahan** [comment]
@elyezer I'm sure there very well is a solution within Nailgun. I'm just trying to push my attrs agenda!

**Comment by elyezer** [comment]
@JacobCallahan that is a good library. I am trying to find the easiest and fastest path to go.

Once we have all options we can decide what should be the decision we are going to make.

**Comment by ehelms** [comment]
Anything I can do to help push this along? I am reliant on this ability to do the next stages of some Ansible and Nailgun work.

**Comment by rochacbruno** [comment]
@ehelms is that enough if we add a method `entity.to_json()` so you can explicitly call it?
 or do you need some automagic such a JsonEnconder or `__repr__` becoming the json representation?

**Comment by ehelms** [comment]
The method should be fine I think, I can double check to see what Ansible
is doing but I think they are following standard serialization paradigms.

**Comment by omaciel** [comment]
@ehelms got any update for us? You were going to check what Ansible does.

@rochacbruno assuming we use your approach, got an ETA for when this can be done?

**Comment by renzon** [comment]
Once Entity has _fields, would be easier using those properties to create the to_json method?

**Comment by ehelms** [comment]
Ansible does a to_json from my research, however, it does this after calling (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L359) which if you notice can only accept basic Python types and errors out when a custom data structure is encountered such as a Nailgun class. This necessitates the module code performing the to json before calling Ansible's json methods to return values.

**Comment by omaciel** [comment]
@renzon ping?
