### ISSUE TITLE
Research Host.puppet_ca_proxy

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/nailgun#35]
The semantics of the `Host.puppet_ca_proxy` field are not well understood. As a result, the field is omitted. The API documentation mentions it, though. From the API documentation:

> POST /api/hosts
> host[puppet_ca_proxy_id]
> Value: Must be a number.

Research the semantics of this field and add it to `nailgun.entities` if appropriate.

**Comment by oshtaier** [comment]
Covered in https://github.com/SatelliteQE/nailgun/pull/255
