### ISSUE TITLE
entities compare should ignore unique fields

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/nailgun#362]
When comparing 2 entities

```python
entity2 = entity1.clone()
entity2 == entity1
False
```

It will always return False, when entity has unique fields as `id` and others.

So we need to find some way in `__eq__` to remove that unique fields when comparing, or provide helper method for that.

**Comment by renzon** [comment]
How can we identify all of them? If it's hard to do for all, let's start with id and include others while people start to use it.

**Comment by renzon** [comment]
Looking into your description I will try an idea: doing assertEqual(ent, ent.clone()) for all entities

**Comment by rochacbruno** [comment]
@renzon someway in the entity field definition we should have `is_unique` property, then we can use to identify.

**Comment by renzon** [comment]
I thought Entity had some 'clone' method which was taken into consideration. But I realized there isn't, so unique values are only defined on server, not on nailgun. So I am going to check all entities and create this new attribute on descriptor.
