### ISSUE TITLE
[Question] Drop ServerConfig from entity __repr__

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/nailgun#378]
Most entities contain some amount of sub-entities. Each entity with all its sub-entities contains separate ServerConfig. When we output some entity, altogether with entity fields and sub-entities we receive a lot of ServerConfig reprs (usually around 5-10, but sometimes much more of them) which are not very useful for user who wants to see what fields does the entity contain in most cases.

My suggestion is to drop ServerConfig from Entity's `__repr__` method, this way we'll reduce the output _a lot_ (in most cases it'll be 2-5 times shorter) and the output will become much more readable.

Just compare:

# Before:
In [2]: entities.Host().create(True)
Out[2]: nailgun.entities.Host(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), comment=None, domain=nailgun.entities.Domain(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=7), managed=True, ip=None, image=None, provision_method=u'build', hostgroup=None, owner=nailgun.entities.User(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=3), operatingsystem=nailgun.entities.OperatingSystem(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=7), subnet=None, realm=None, capabilities=[u'build'], id=7, environment=nailgun.entities.Environment(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=7), build=False, host_parameters_attributes=[], puppet_ca_proxy=None, ptable=nailgun.entities.PartitionTable(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=112), location=nailgun.entities.Location(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=14), medium=nailgun.entities.Media(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=14), puppetclass=[], compute_profile=None, mac=u'b7:34:f5:32:ac:ff', interface=[nailgun.entities.Interface(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), host=nailgun.entities.Host(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=7), id=14)], puppet_proxy=None, owner_type=u'User', name=u'xrgmstxvip.helug5troh', enabled=True, compute_resource=None, architecture=nailgun.entities.Architecture(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=8), organization=nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=15), model=None)

# After:
In [2]: entities.Host().create(True)
Out[2]: nailgun.entities.Host(comment=None, domain=nailgun.entities.Domain(id=6), managed=True, ip=None, image=None, provision_method=u'build', hostgroup=None, owner=nailgun.entities.User(id=3), operatingsystem=nailgun.entities.OperatingSystem(id=6), subnet=None, realm=None, capabilities=[u'build'], id=6, environment=nailgun.entities.Environment(id=6), build=False, host_parameters_attributes=[], puppet_ca_proxy=None, ptable=nailgun.entities.PartitionTable(id=111), location=nailgun.entities.Location(id=11), medium=nailgun.entities.Media(id=13), puppetclass=[], compute_profile=None, mac=u'88:25:fe:93:fd:cd', interface=[nailgun.entities.Interface(host=nailgun.entities.Host(id=6), id=13)], puppet_proxy=None, owner_type=u'User', name=u'sgjdotcmnz.h0w8ar7kp9', enabled=True, compute_resource=None, architecture=nailgun.entities.Architecture(id=7), organization=nailgun.entities.Organization(id=12), model=None)

#  

So my question is, should we output ServerConfig of each entity each time or maybe we can drop it?

Another small bonus of dropping ServerConfig from output is we won't have to replace actual server address each time we paste the output to github.

And the change itself is pretty trivial:
```diff
diff --git a/nailgun/entity_mixins.py b/nailgun/entity_mixins.py
index d6e758e..e64051f 100644
--- a/nailgun/entity_mixins.py
+++ b/nailgun/entity_mixins.py
@@ -512,12 +512,11 @@ class Entity(object):
         return attrs

     def __repr__(self):
-        return '{0}.{1}({2}{3})'.format(
+        return '{0}.{1}({2})'.format(
             self.__module__,
             type(self).__name__,
-            repr(self._server_config),
-            ''.join(
-                ', {0}={1}'.format(key, repr(value))
+            ', '.join(
+                '{0}={1}'.format(key, repr(value))
                 for key, value
                 in self.get_values().items()
             )
```

**Comment by abalakh** [comment]
@oshtaier @svtkachenko @rochacbruno  @omaciel @elyezer @Ichimonji10 guys, i'd like to hear your thoughts on this.
Personally, i never found ServerConfig info useful to output each time without asking, it always just generates a lot of spam in which i can barely see actual fields with values.
And in case somebody really wants to play with different serverconfigs inside the single entity (i'm not even sure if that's a real use case) - we aren't dropping it actually, it can be easily returned with `EntityName._server_config`.

**Comment by elyezer** [comment]
From the docs [1]: "If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment)."

What you can use is the `reprlib` (repr on Python 2) to summarize long object's field. That could be applied to the ServerConfig URL settings.

Worth stress that "if at all possible" from the docs. I am suggesting the reprlib just in case it would be as close as possible to what Python does, but if that will not provide any benefit to NailGun then we can just drop it. Whatever you guys decide will be fine to me.

[1] https://docs.python.org/2/reference/datamodel.html?highlight=__repr__#object.__repr__

**Comment by rochacbruno** [comment]
@elyezer if we try to recreate the object from the `__repr__` even without server config it must be created and server config set to defaults no?

I vote +1 to remove that info from `__repr__` so we end with clean logs and easier to debug outputs.

**Comment by abalakh** [comment]
Exactly, if ServerConfig is not specified explicitly - the default one (your 'current' one) will be used. Dropping ServerConfig from `__repr__`` will even give us a bit more flexibility - we can recreate the entity for any server we may want to use, not just the server where entity was originally defined.

**Comment by elyezer** [comment]
Fair enough, let's drop it then :smile:
