### ISSUE TITLE
Credentials in plaintext in read() functions

### ISSUE THREAD

**Issue by tryfan** [SatelliteQE/nailgun#405]
I'm using a simple read operation with:

username = raw_input("Username: ")
password = getpass("Password: ")
server_config = ServerConfig(
       auth=(username,password),
       url='https://satellite',
)
org = Organization(server_config, id=1).read()
  pprint(org.get_values())

'title': u'Default Organization',
 'user': [nailgun.entities.User(nailgun.config.ServerConfig(url='https://satellite', verify=False, auth=('user', 'hunter2')), id=20),
          nailgun.entities.User(nailgun.config.ServerConfig(url='https://satellite', verify=False, auth=('user', 'hunter2')), id=22),
          nailgun.entities.User(nailgun.config.ServerConfig(url='https://satellite', verify=False, auth=('user', 'hunter2')), id=16),
          nailgun.entities.User(nailgun.config.ServerConfig(url='https://satellite', verify=False, auth=('user', 'hunter2')), id=12),
          nailgun.entities.User(nailgun.config.ServerConfig(url='https://satellite', verify=False, auth=('user', 'hunter2')), id=29),
          nailgun.entities.User(nailgun.config.ServerConfig(url='https://satellite', verify=False, auth=('user', 'hunter2')), id=7)]

The password is viewable in plaintext on output.  The password, at the very least, should be redacted and only viewable by flagging a plaintext password variable in the read function.

**Comment by rochacbruno** [comment]
@ncelebic good catch! I am going to find a way to fix this.

**Comment by rochacbruno** [comment]
I am thinking about obfuscating the password on ServerConfig `__repr__`

@elyezer what do you think?

**Comment by elyezer** [comment]
@rochacbruno I think having the password visible is useful when using Nailgun to write tests. But I think it should not be enabled by default. Like it would be great to mask the password by default but have an option to not do that.

**Comment by ncelebic** [comment]
That was the idea.  For debugging, having it visible makes sense.  By default it should definitely obfuscate them, if not omit them entirely.
