### ISSUE TITLE
"settings" cannot be tested

### ISSUE THREAD

**Issue by thomasmckay** [SatelliteQE/nailgun#468]
Am I wrong that there is not a "settings" module? I want to use them through foreman-ansible-modules

**Comment by omaciel** [comment]
There is a `Settings` entity: https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L5644

**Comment by san7ket** [comment]
@thomasmckay Does this answer what you asked for? or do you have something else in mind
