### ISSUE TITLE
Release a new version of Nailgun

### ISSUE THREAD

**Issue by evgeni** [SatelliteQE/nailgun#520]
There have been quite a number of changes since the last Nailgun release, 4 months ago. It's time to kick off a new version. :)

**Comment by san7ket** [comment]
Just one open PR remains , will try to wrap it up ASAP, then we will branch and release

**Comment by ehelms** [comment]
Would you mind linking the last remaining PR so we know what to keep an eye on?

**Comment by san7ket** [comment]
We will hold the PR and release , already branched to 6.4.z

**Comment by san7ket** [comment]
Closing the issue. Nailgun released to 0.31.0
