### ISSUE TITLE
Create and Document the Nailgun Processes

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/nailgun#553]
For now, we are creating a rough draft of the processes that would make easier for contributions and review.
We are still at the initial phase, and will share across the document, once we get it outline and structure ready.
I would like everyone to participate to develop this, so that it would benefit the project and all other projects that consume nailgun.

**Comment by oshtaier** [comment]
First of all, I think we need to enforce common sense things:
1) Keep the same style, standards and approach that code already has. That basically means, if people followed something for years that something has reasons behind.
2) First comment for every PR should contain test results that prove code is working. That means we, of course, trust every contributor commit, but let's be respectful to each other
3) At least two ACKs per each PR and more in case something changed to fundamental, basic architecture
4) Continue add unit tests at least in a way we did till that moment
5) That is fine to ping people in polite manner and if you are ready for constructive feedback

Will add more if remember something

**Comment by sean797** [comment]
> Keep the same style, standards and approach that code already has. That basically means, if people followed something for years that something has reasons behind. Want to change it - provide reasons, don't wait that people behind existing approach provide reasons to you

It easy to make a change an not see "style, standards or approach" where you do. Any style or standards we want to enfore we should ideally do via linitng tests.

> First comment for every PR should contain test results that prove code is working.

I strongly disagree with this, data like this provide little to no value. There is a whole load of reasons why something that works for the contributor, does not work somewhere else. Consistent contributors should test a contribution before raising a PR.


> but let's be respectful to each other

I'm glad you said that.

**Comment by oshtaier** [comment]
>It easy to make a change an not see "style, standards or approach" where you do. Any style or standards we want to enfore we should ideally do via linitng tests.
Okay, till we get to more lint tests and till contributor open his or her eyes to see obviously same/similar code in other methods we have to have proper review procedure. That still get us to the point that we need people who familiar with a framework to merge properly formed code from some dev branch to the master. And everyone who doesn't have time can use that dev branch for himself and his projects. We need to isolate proper commits and commits that done according some selfish rules.

>I strongly disagree with this, data like this provide little to no value. There is a whole load of reasons why something that works for the contributor, does not work somewhere else. 
Right, but that is only your point. We can provide reasons why that procedure worked for us for years to guarantee some safety even for yourself. Especially, when person fix own code after some review cycles.

>Consistent contributors should test a contribution before raising a PR.
So what's the problem to provide test results if you test something for real

>I'm glad you said that.
I'm glad **you** said that.

**Comment by sean797** [comment]
> There are only two cases there. Whether you test your code or don't. If you do, so what's the problem to provide test results and if you don't, so why you submit it at all?

People test things in different ways, for example, I test using FAM, often in combination with changes I'm making to FAM, the output of the test using FAM are unlikely to mean anything to you. Contributors from SatelliteQE and FAM are not here to make contributions that break things. To a reviewer what value does the contributor copying and pasting his or hers test output provide?

**Comment by oshtaier** [comment]
@sean797 very good question. If we have so different API that test results from one direction is not useful for another, maybe we need to form completely separated branches for FAM and Sat?

**Comment by sean797** [comment]
Having different branches will make making changes across them harder, as you'll have to backport a fix potentially into many different branches. Then there is also the issue of release, how does a user know what release of Nailgun to use with Satellite/Foreman/Katello/FAM version? 

While that is one solution, I believe having master follow upstream master branches and releasing a major version of Nailgun per upstream/downstream release. I think that would allow us to start packaging Nailgun for different releases of servers

For example: (versiosn numbers are not accurate)

Server version | Nailgun version
------------ | -------------
Upstream 1.25 | 0.42
Satellite 6.5 | 0.43, 0.43.1
Upstream 1.26 | 0.44, 0.44.1, 0.44.2
Satellite 6.6 | 0.45

**Comment by sean797** [comment]
I think we need to move away from such a strong Satellite focus within Nailgun, things like testing with potentially unreleased Satellite versions, labels like "6.5" and others make Nailgun somewhat exclusive to Satellite and not conducive to community contributions.

**Comment by sghai** [comment]
> I think we need to move away from such a strong Satellite focus within Nailgun, things like testing with potentially unreleased Satellite versions, labels like "6.5" and others make Nailgun somewhat exclusive to Satellite and not conducive to community contributions.

Robottelo API tests are heavily dependent on Nailgun and our first intent is to minimize the breakages at our test level. Nailgun was designed for Satellite versions only. However, we would like to open it to wider community but without affecting our test cases which are tightly coupled with Nailgun.

I would say lets start from somewhere and see how that goes. As a first step, I would like to improve the review process, which can be done as you suggested @sean797  by branching. 

As a proposal, all changes should merge to develop first. Later, cherry-picking would be done  from develop branch by testing the changes and merge to respective branch of 6.5/6.6. Again, its just a proposal and we are open to improve. I understand there is an overhead of cherry-picking but I feel we should go with it unless someone has any other proposal.  That's the reason we would like to use labels. Additionally, nailgun has both the entities of Katello and foreman and there is no differentiation so that' is the another reason of using "6.x" labels.

**Comment by sean797** [comment]
> Robottelo API tests are heavily dependent on Nailgun and our first intent is to minimize the breakages at our test level. 

@sghai and thats the crux of the issue, the problem with the current focus towards testing Satellite it makes it hard to use it in other use cases. Nailgun should be a library for interacting with the API, there should be any focus on any specific use case.

For example, the `blinker_herald` dependency makes its harder for anyone to package for a distro, I cannot see a good reason why this dependency should be required if all I want to do is use the Foreman/Katello/Satllite API.

**Comment by san7ket** [comment]
Closing this, as we came up with a process for Contributing, Reviewing, Branching and Releasing Nailgun that would benefit all involved communities consuming Nailgun.
This discsussion as lead to some action Items which will be tracked in https://github.com/SatelliteQE/nailgun/projects/1
If there are any more issue, feel free to raise them and link it to the project.
