### ISSUE TITLE
Create PR and Issue templates for nailgun

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/nailgun#578]
* PR should follow a template:
a) Summary - Description of change
b) Issue Type - Bug Fix or new addition/enhancement
c) Component - e.g. Activation key/Repository etc.

**Comment by oshtaier** [comment]
About output. In my opinion it should be exact output of your usage of framework no matter where you use it. Something like:
```
>python
>>>from nailgun import entities
>>> architecture = entities.Architecture(name='test1').create()
>>> architecture
nailgun.entities.Architecture(name='test1', operatingsystem=[], id=10)
```
That part is most important
```
nailgun.entities.Organization(my_new_attribute='new')
```
That output is pretty much independent from type of application you use

**Comment by san7ket** [comment]
@sean797 Yesterday had a discussion with @evgeni , and he suggested what if we add this as a docstring in the code itself, this way whenever some one uses the entity, he could look into usage example

**Comment by sean797** [comment]
>  he suggested what if we add this as a docstring in the code itself, this way whenever some one uses the entity, he could look into usage example

That makes sense :+1:

**Comment by san7ket** [comment]
Edited the issue, the template is basically to identity the component and then later suggest a reviewer, or also if applicable, to cherry-pick the PR in stable branches

**Comment by mdellweg** [comment]
> @sean797 Yesterday had a discussion with @evgeni , and he suggested what if we add this as a docstring in the code itself, this way whenever some one uses the entity, he could look into usage example

This could go well together with `doctest`.
https://docs.python.org/2/library/doctest.html
