### ISSUE TITLE
Branch Nailgun for satellite

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/nailgun#580]

**Comment by san7ket** [comment]
@evgeni @sean797 We will need to branch for 6.5 soon.

**Comment by mirzal** [comment]
We kind of naturally follow Robottelo branches, which are named after Satellite versions. So we have 6.4.z, 6.5.z and master which follows what will be Satellite 6.6.

@san7ket is there anything else needed for this ticket, or can we close it?

**Comment by san7ket** [comment]
We have branched to stable-satellite, which will act as a master branch for satellite.
