### ISSUE TITLE
how to invoke remote execution job via Nailgun?

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/nailgun#623]
I have found this in our tests, but that looks bit hacky:

```
    invocation_command = entities.JobInvocation().run(data={
        'job_template_id': template.id,
        'inputs': {'command': "ls"},
        'targeting_type': 'static_query',
        'search_query': "name ~ {0}".format(host.name)
    })
```

Is something like `TemplateInvocation` missing? Or is that a right way to do it?

CC @rplevka

**Comment by oshtaier** [comment]
That was the only one way in the past, but a lot of time passed since, so if you feel there is another, please share it

**Comment by jhutar** [comment]
I do not know. How do I determine it please?

**Comment by oshtaier** [comment]
You mentioned `TemplateInvocation` which didn't exist at all in the past. Anyway, what is wrong with `JobInvocation` way you described above?

**Comment by jhutar** [comment]
If it is supposed to work that way, then great! Maybe normal pattern `x = entities.Something(...).create()` and then work with `x` wont makes sense here?

**Comment by oshtaier** [comment]
even in webUI, it is:
![image](https://user-images.githubusercontent.com/10895065/54357973-f0f9f680-4667-11e9-9288-d8c9860194c4.png)

So there is no `job.create`, but rather `job.run`

**Comment by jhutar** [comment]
OKi, thanks!
