### ISSUE TITLE
Drop Py2 from nailgun and stop building for Py2

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/nailgun#648]
Thoughts ?? Concerns??

**Comment by evgeni** [comment]
This would mean that you can't use `nailgun` in [foreman-ansible-modules](https://github.com/theforeman/foreman-ansible-modules) on EL7.

Long term this is fine as we're moving away from using `nailgun`, but we're not quite there yet.
When do you want to ditch Python2 support?

**Comment by evgeni** [comment]
cc @ehelms @Fobhep @mdellweg @akofink for awareness wrt FAM

**Comment by san7ket** [comment]
Not immediately, we can wait if there are dependencies. This is not blocking. 
Just wanted to hear thoughts on this

**Comment by evgeni** [comment]
@san7ket you have an approximate time when you'd *like* to have this? Would help with prioritizing our migration (currently it's more a "as time permits" thing).

**Comment by san7ket** [comment]
Nope, we won't be doing this , until any hard requirements comes up. Atleast , today having py2 doesn't affect us. 
I see no such requirements, again just wanted to be aware if there are any dependencies. 

Now, that there are, we will hold this off, until we are in clear.

**Comment by san7ket** [comment]
Closing this issue, as there are dependencies and there is no requirements for us to drop Py2.
