### ISSUE TITLE
Validate file_count property for ContentViewVersion

### ISSUE THREAD

**Issue by JacobCallahan** [SatelliteQE/nailgun#782]
We're seeing a key error in tests trying to read content view versions in Sat 6.9 snaps.
We will need someone to validate whether or not this field should exist in 6.9.
If it no longer exists, then the field needs to be removed from nailgun's ContentViewVersion entity.

**Comment by latran** [comment]
@JacobCallahan Is this on API, CLI, or UI?  I'm investigating at the moment.

**Comment by JacobCallahan** [comment]
@latran this is API.

**Comment by latran** [comment]
@JacobCallahan It's in use as far as I have seen.  where are the specific key errors in the tests that you're seeing?

**Comment by latran** [comment]
Closing out this issue as the API have all passed on my local run.  Will reopen if issue reoccurs.
