### ISSUE TITLE
Make sure that all entities that inherit CreateMixin have ReadMixin

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/nailgun#86]
Since `EntityCreateMixing.create` relies on  `EntityReadMixin.read` all entities that inherit from the create mixing should inherit also from the read mixin.

Other approach is to make the create check for the presence of the `read` method and raise an exception if not present making the user aware of that the read mixin is needed.

**Comment by elyezer** [comment]
Currently the only entity which inherit from the create but not from the read is `HostGroup`.

**Comment by Ichimonji10** [comment]
:+1:

**Comment by Ichimonji10** [comment]
Fixed by #84.
