### ISSUE TITLE
[Failed-AutoCherryPick] - Play ansible roles on host

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/nailgun#947]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.12.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/nailgun/actions/runs/5440611379)
- [Parent Pull Request](https://github.com/SatelliteQE/nailgun/pull/936)

**Comment by Gauravtalreja1** [comment]
Seems already fixed in https://github.com/SatelliteQE/nailgun/pull/960 by @lhellebr, please be keep in mind next to link failed autocherrypick issue in PR, closing this issue as completed.
